import {
  Shield, Users, TrendingUp, Briefcase, User, CheckCircle, XCircle, Target, BriefcaseBusiness, FilePlus
} from "lucide-react";

// --- DATA FOR THE PAGE ---

const featuresData = [
    { icon: User, title: "One-Man Ownership & Control" },
    { icon: FilePlus, title: "Minimal Legal Formalities" },
    { icon: BriefcaseBusiness, title: "Owner's Capital Contribution" },
    { icon: Shield, title: "Unlimited Liability" },
    { icon: Users, title: "No Separate Legal Entity" },
    { icon: TrendingUp, title: "No Profit Sharing" },
];

const benefitsData = [
    "Easiest and least expensive form of ownership to organize.",
    "The sole proprietor is in complete control and can make decisions freely.",
    "All income generated by the business flows directly to the owner.",
    "Business profits are taxed on the owner's personal tax return.",
    "The business is simple to dissolve if desired.",
];

const limitationsData = [
    "The owner has unlimited liability, meaning personal assets are at risk.",
    "Raising funds is often difficult and limited to personal savings or consumer loans.",
    "It can be challenging to attract high-caliber employees who may seek ownership opportunities.",
];

const suitabilityData = [
    "Ventures where the capital requirement is very small.",
    "Businesses involving artistic skills or personal services.",
    "Operations that necessitate a high degree of cooperation and direct control.",
    "Early-stage computer services and freelance work.",
];

const procedureData = [
    "Decide on a unique and appropriate business name.",
    "Conduct a search to ensure the name is available and not similar to existing names.",
    "Register the business name as a proprietorship.",
    "Apply for a business PAN card and open a dedicated bank account.",
];

const whyChooseUsData = [
  {
    icon: Shield,
    title: "Deep Regulatory Expertise",
    description: "Our team possesses an in-depth understanding of India's complex regulatory landscape, ensuring your compliance from day one.",
  },
  {
    icon: Users,
    title: "Tailored Entry Strategies",
    description: "We analyze your business goals to devise a bespoke market entry strategy that minimizes risk and maximizes potential.",
  },
  {
    icon: TrendingUp,
    title: "Proven Growth Partners",
    description: "We act as your strategic partners, offering ongoing advisory to help you scale and succeed in the Indian market.",
  },
  {
    icon: Briefcase,
    title: "End-to-End Service",
    description: "We provide a single point of contact for all your business needs in India, simplifying your operations.",
  },
];

const ProprietorshipPage = () => {
  return (
    <>
      {/* Section 1: Hero */}
      <section
        className="relative h-[50vh] text-white bg-cover bg-center bg-no-repeat"
        style={{ backgroundImage: `url(/Sole-Proprietorship-Registration-1038x576.webp)` }}
      >
        <div className="absolute inset-0 bg-black/60"></div>
        <div className="relative z-10 h-full flex flex-col items-center justify-center text-center px-4">
          <h1 className="text-5xl md:text-6xl font-bold leading-tight drop-shadow-lg">Sole Proprietorship</h1>
          <p className="text-xl mt-4 max-w-3xl opacity-90">The Simplest Path to Starting Your Business Venture.</p>
        </div>
      </section>

      {/* Section 2: Introduction */}
      <section className="py-20 bg-background">
        <div className="container mx-auto px-4 max-w-4xl text-center">
            <h2 className="text-4xl font-bold text-foreground mb-6">What is a Sole Proprietorship?</h2>
            <div className="prose lg:prose-lg max-w-none text-muted-foreground mx-auto text-left">
                <p>A sole proprietorship is an unincorporated business owned and run by one individual with no legal distinction between the owner and the business entity. The owner is personally responsible for all of the business's assets and liabilities and is entitled to all profits earned. It represents the most straightforward business structure, allowing for complete control and simplified management.</p>
            </div>
        </div>
      </section>
      
      {/* Section 3: Features, Benefits, Limitations & Suitability */}
      <section className="py-20 bg-gray-50">
          <div className="container mx-auto px-4 space-y-20">
              
              {/* Key Features */}
              <div>
                  <h2 className="text-3xl font-bold text-foreground text-center mb-12">Key Features of a Proprietorship</h2>
                  <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8 max-w-5xl mx-auto">
                      {featuresData.map(item => {
                          const Icon = item.icon;
                          return <div key={item.title} className="bg-card p-6 rounded-lg flex items-center gap-4 border shadow-sm"><Icon className="w-8 h-8 text-primary flex-shrink-0" />
                          <h3 className="text-lg font-semibold text-foreground">{item.title}</h3></div>
                      })}
                  </div>
              </div>

              {/* Benefits vs. Limitations */}
              <div>
                  <div className="grid lg:grid-cols-2 gap-12">
                      <div className="bg-card p-8 rounded-lg shadow-lg border">
                          <h3 className="text-2xl font-bold text-foreground mb-6 text-center">Benefits</h3>
                          <ul className="space-y-4">
                              {benefitsData.map(item => (
                                  <li key={item} className="flex items-start"><CheckCircle className="w-6 h-6 text-green-500 mr-3 mt-1 flex-shrink-0" />
                                  <span className="text-muted-foreground">{item}</span></li>
                              ))}
                          </ul>
                      </div>
                      <div className="bg-card p-8 rounded-lg shadow-lg border">
                           <h3 className="text-2xl font-bold text-foreground mb-6 text-center">Limitations</h3>
                           <ul className="space-y-4">
                              {limitationsData.map(item => (
                                  <li key={item} className="flex items-start"><XCircle className="w-6 h-6 text-red-500 mr-3 mt-1 flex-shrink-0" />
                                  <span className="text-muted-foreground">{item}</span></li>
                              ))}
                          </ul>
                      </div>
                  </div>
              </div>

              {/* Suitability & Commencement */}
              <div className="grid lg:grid-cols-2 gap-12 items-start">
                  <div className="bg-card p-8 rounded-lg shadow-lg border">
                      <h3 className="text-2xl font-bold text-foreground mb-6">Best Suited For</h3>
                      <ul className="space-y-4">
                          {suitabilityData.map(item => (
                              <li key={item} className="flex items-start"><Target className="w-6 h-6 text-primary mr-3 mt-1 flex-shrink-0" />
                              <span className="text-muted-foreground">{item}</span></li>
                          ))}
      
                          </ul>
                  </div>
                   <div className="bg-card p-8 rounded-lg shadow-lg border">
                      <h3 className="text-2xl font-bold text-foreground mb-6">Commencement Procedure</h3>
                      <ul className="space-y-4">
                          {procedureData.map((item, index) => (
                              <li key={item} className="flex items-start">
                                <div className="bg-primary text-primary-foreground w-8 h-8 rounded-full flex items-center justify-center font-bold mr-4 flex-shrink-0">{index + 1}</div>
                                <span className="text-muted-foreground text-lg">{item}</span>
                              </li>
                          ))}
                      </ul>
                  </div>
              </div>
          </div>
      </section>

      {/* Section 4: Why Choose Us */}
      <section className="py-20 bg-background">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold text-foreground mb-4">Why Choose Pritam Ajit & Company?</h2>
          <p className="text-lg text-muted-foreground max-w-3xl mx-auto mb-16">Your success is our business. We provide the expertise and partnership you need to navigate and thrive in the Indian market.</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {whyChooseUsData.map((card, index) => {
              const Icon = card.icon;
              return (
                <div key={index} className="bg-card p-8 rounded-lg shadow-sm border border-transparent hover:border-primary hover:shadow-lg hover:-translate-y-2 transition-all duration-300 ease-in-out">
                  <div className="flex justify-center mb-6">
                    <div className="bg-primary/10 p-4 rounded-full">
                      <Icon className="h-8 w-8 text-primary" />
                    </div>
                  </div>
                  <h3 className="text-xl font-semibold text-foreground mb-3">{card.title}</h3>
                  <p className="text-muted-foreground">{card.description}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>
    </>
  );
};

export default ProprietorshipPage;